# Generated by Django 3.1.5 on 2021-01-14 11:44

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210113_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='location',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='example:09121112020', max_length=11, null=True, unique=True, validators=[profiles.models.VALID]),
        ),
    ]
