# Generated by Django 3.1.5 on 2021-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210114_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.SlugField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
