# Generated by Django 3.1.5 on 2021-01-14 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210114_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
